- name: Deploy to Kubernetes
  hosts: local
  gather_facts: true
  vars_files:
    - group_vars/all/vault.yml
  tasks:

    # --- Dependencies (unchanged) ---
    - name: Check if Minikube exists
      stat:
        path: /usr/local/bin/minikube
      register: minikube_stat

    - name: Download and Install Minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'
      become: true
      when: not minikube_stat.stat.exists

    - name: Check if kubectl exists
      stat:
        path: /usr/local/bin/kubectl
      register: kubectl_stat

    - name: Download and Install kubectl
      get_url:
        url: "https://dl.k8s.io/release/v1.28.2/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
      become: true
      when: not kubectl_stat.stat.exists

    # --- CHANGED SECTION START ---
    
    # REMOVED: "Try to stop Minikube" and "Delete Minikube" tasks.
    # We want to keep the cluster running to ensure zero downtime.

    - name: Ensure Minikube is Running
      command: minikube start --driver=docker --memory=8192 --cpus=4
      # This command is idempotent. If Minikube is already running, 
      # it simply verifies the status without interrupting services.

    # --- CHANGED SECTION END ---

    - name: Enable Metrics Server Addon
      command: minikube addons enable metrics-server

    - name: Force Delete Stuck Mongo Deployment
      command: minikube kubectl -- delete deployment mongo --ignore-not-found=true

    - name: Apply All Kubernetes Manifests
      shell: |
        for f in k8s/*.yaml; do echo "---"; cat "$f"; echo; done | sed 's/DOCKER_USER_PLACEHOLDER/{{ docker_user }}/g' | sed 's/EMAIL_USER_PLACEHOLDER/{{ email_user_b64 }}/g' | sed 's/EMAIL_PASS_PLACEHOLDER/{{ email_pass_b64 }}/g' | minikube kubectl -- apply -f -
      register: deploy_output

    - name: Show Deployment Output
      debug:
        var: deploy_output.stdout_lines

    # --- NEW TASK ---
    - name: Trigger Rolling Restart for Zero Downtime Update
      command: minikube kubectl -- rollout restart deployment/{{ item }}
      loop:
        - mongo
        - auth-service
        - campaign-service
        - assessment-service
        - student-service
        - dashboard-service
        - gateway
        - client
      # This ensures that even if only configuration (Env vars/Secrets) changed,
      # the pods are cycled gracefully (start new -> wait for ready -> kill old).

    - name: Wait for all deployments to be ready
      command: minikube kubectl -- rollout status deployment/{{ item }}
      loop:
        - mongo
        - auth-service
        - campaign-service
        - assessment-service
        - student-service
        - dashboard-service
        - gateway
        - client

    - name: Deploy ELK Stack
      include_role:
        name: elk

